'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Captura
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''equipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents equipo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblEquipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEquipo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''inicio_perf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inicio_perf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''equipo_perf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents equipo_perf As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''fin_perf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fin_perf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tipo_pozo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tipo_pozo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Max_Inclinacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Max_Inclinacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Max_dls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Max_dls As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fecha_ultima_int control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fecha_ultima_int As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ult_rep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ult_rep As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fc_ult_int control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fc_ult_int As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''flu_ctrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents flu_ctrl As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fec_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fec_inicio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hora_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hora_inicio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fec_actual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fec_actual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hora_actual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hora_actual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''prod_ant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prod_ant As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''prod_act control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prod_act As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dia_p_trans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dia_p_trans As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dia_p_op control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dia_p_op As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dia_p_tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dia_p_tot As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dia_r_trans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dia_r_trans As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dia_r_op control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dia_r_op As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dia_r_real control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dia_r_real As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''objetivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objetivo As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''operacion_actual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operacion_actual As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''programa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents programa As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''isp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isp As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ip As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents c As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pozo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pozo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''macropera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents macropera As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sector As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''proftotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents proftotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''profvert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profvert As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''seccionvert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents seccionvert As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tipodeint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tipodeint As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''abrevdeint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents abrevdeint As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''compañia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents compañia As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''actgeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actgeneral As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''costprog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents costprog As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fecha_termprog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fecha_termprog As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fecha_reto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fecha_reto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fec_inicio_mov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fec_inicio_mov As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hora_inic_mov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hora_inic_mov As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fec_term_mov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fec_term_mov As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hora_term_mov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hora_term_mov As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cap_equipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cap_equipo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''prox_mov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prox_mov As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''abrev_intprox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents abrev_intprox As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''macropera_proxmov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents macropera_proxmov As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''op_ant_resumen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents op_ant_resumen As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''observaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents observaciones As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''pendientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pendientes As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''edo_actual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents edo_actual As Global.System.Web.UI.HtmlControls.HtmlInputFile
    
    '''<summary>
    '''edo_prog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents edo_prog As Global.System.Web.UI.WebControls.FileUpload
End Class
